Remove the code the verifies the existence of the binary to each OS-specific installation step so we can keep a generic call to each coveralls command and not have to create OS-specific steps for those too.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -83,11 +83,17 @@ runs:
         brew tap coverallsapp/coveralls --quiet
         brew install coveralls --quiet
 
+        # Check if the binary exists in the expected location
+        if [ ! -f /usr/local/bin/coveralls ]; then
+          echo "Coveralls binary not found after installation (MacOS)."
+          exit 1
+        fi
+
     - name: Report coverage-reporter-version information for macOS
       if: ${{ runner.os == 'macOS' && inputs.coverage-reporter-version != 'latest' }}
       shell: bash
       run: |
-        echo "The coverage-reporter-version parameter is not available on macOS" >&2
+        echo "The coverage-reporter-version parameter is not available on macOS." >&2
         exit 1
 
     - name: Install coveralls reporter (Linux)
@@ -111,7 +117,7 @@ runs:
         # Try to download the binary and checksum file
         if ! curl -sLO "https://github.com/coverallsapp/coverage-reporter/releases/${asset_path}/coveralls-linux.tar.gz" ||
           ! curl -sLO "https://github.com/coverallsapp/coverage-reporter/releases/${asset_path}/coveralls-checksums.txt"; then
-          echo "Failed to download coveralls binary or checksum."
+          echo "Failed to download coveralls binary or checksum (Linux)."
           [ "${{ inputs.fail-on-error }}" == "false" ] && exit 0
           exit 1
         fi
@@ -124,7 +130,7 @@ runs:
 
         # Verify the downloaded binary
         if ! grep coveralls-linux.tar.gz coveralls-checksums.txt | sha256sum --check; then
-          echo "Checksum verification failed."
+          echo "Checksum verification failed (Linux)."
           [ "${{ inputs.fail-on-error }}" == "false" ] && exit 0
           exit 1
         fi
@@ -141,6 +147,12 @@ runs:
         rm coveralls-checksums.txt
         echo ~/bin >> $GITHUB_PATH
 
+        # Check if the binary exists
+        if [ ! -f ~/bin/coveralls ]; then
+          echo "Coveralls binary not found after extraction (Linux)."
+          exit 1
+        fi
+
     - name: Install coveralls reporter (Windows)
       if: startsWith(runner.os, 'Windows')
       env:
@@ -156,22 +168,28 @@ runs:
           Invoke-WebRequest -Uri "https://github.com/coverallsapp/coverage-reporter/releases/download/$env:COVERAGE_REPORTER_VERSION/coveralls-windows.exe" -OutFile "coveralls.exe"
           Invoke-WebRequest -Uri "https://github.com/coverallsapp/coverage-reporter/releases/download/$env:COVERAGE_REPORTER_VERSION/coveralls-checksums.txt" -OutFile "sha256sums.txt"
         }
-        (Get-FileHash coveralls.exe).Hash -eq (Get-Content ./sha256sums.txt | Where-Object{$_ -match 'windows.exe'} | ForEach-Object{($_ -split "\s+")[0]})
-        Remove-Item *.txt -Force
+        
+        if ((Get-FileHash coveralls.exe).Hash -ne (Get-Content sha256sums.txt | Select-String 'windows.exe' | ForEach-Object { ($_ -split "\s+")[0] })) {
+          Write-Host "Checksum verification failed (Windows)."
+          exit 1
+        }
+
+        # Check if the binary exists
+        if (!(Test-Path -Path "$env:HOME\bin\coveralls.exe")) {
+          Write-Host "Coveralls binary not found after download and verification (Windows)."
+          exit 1
+        }
+
+        Remove-Item sha256sums.txt -Force
         echo $env:HOME\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
     - name: Done report
       if: inputs.parallel-finished == 'true'
       shell: ${{ startsWith(runner.os, 'Windows') && 'pwsh' || 'bash' }}
-      run: |
-        if [ ! -f ~/bin/coveralls ]; then
-          echo "Coveralls binary not found."
-          [ "${{ inputs.fail-on-error }}" == "false" ] && exit 0
-          exit 1
-        fi
-        ~/bin/coveralls done \
-        ${{ inputs.debug == 'true' && '--debug' || '' }} \
-        ${{ inputs.measure == 'true' && '--measure' || '' }} \
+      run: >-
+        coveralls done
+        ${{ inputs.debug == 'true' && '--debug' || '' }}
+        ${{ inputs.measure == 'true' && '--measure' || '' }}
         ${{ inputs.fail-on-error == 'false' && '--no-fail' || '' }}
       env:
         COVERALLS_DEBUG: ${{ inputs.debug }}
@@ -186,20 +204,15 @@ runs:
     - name: Coverage report
       if: inputs.parallel-finished != 'true'
       shell: ${{ startsWith(runner.os, 'Windows') && 'pwsh' || 'bash' }}
-      run: |
-        if [ ! -f ~/bin/coveralls ]; then
-          echo "Coveralls binary not found."
-          [ "${{ inputs.fail-on-error }}" == "false" ] && exit 0
-          exit 1
-        fi
-        ~/bin/coveralls report \
-        ${{ inputs.debug == 'true' && '--debug' || '' }} \
-        ${{ inputs.measure == 'true' && '--measure' || '' }} \
-        ${{ inputs.fail-on-error == 'false' && '--no-fail' || '' }} \
-        ${{ inputs.allow-empty == 'true' && '--allow-empty' || '' }} \
-        ${{ inputs.base-path && format('--base-path {0}', inputs.base-path) || '' }} \
-        ${{ inputs.format && format('--format {0}', inputs.format) || '' }} \
-        ${{ inputs.file || inputs.path-to-lcov }} \
+      run: >-
+        coveralls report
+        ${{ inputs.debug == 'true' && '--debug' || '' }}
+        ${{ inputs.measure == 'true' && '--measure' || '' }}
+        ${{ inputs.fail-on-error == 'false' && '--no-fail' || '' }}
+        ${{ inputs.allow-empty == 'true' && '--allow-empty' || '' }}
+        ${{ inputs.base-path && format('--base-path {0}', inputs.base-path) || '' }}
+        ${{ inputs.format && format('--format {0}', inputs.format) || '' }}
+        ${{ inputs.file || inputs.path-to-lcov }}
         ${{ inputs.files }}
       env:
         COVERALLS_DEBUG: ${{ inputs.debug }}
